# Renumbered Combined Python & JavaScript Challenges
challenges_list = {
    "B01": "Even or Odd Checker - Ask the user for a number and print whether it's even or odd. (Python)",
    "B02": "Number Guessing Game - Generate a random number between 1 and 10, and ask the user to guess it. (Python)",
    "B03": "Simple Calculator - Let the user input two numbers and an operator (+, -, *, /) and return the result. (Python)",
    "B04": "Palindrome Checker - Check if a given string (like 'radar') reads the same backward. (Python)",
    "B05": "Multiplication Table Generator - Ask the user for a number and print its multiplication table up to 10. (Python)",
    "B06": "Countdown Timer - Ask for a number of seconds, and count down to 0, printing each second. (Python)",
    "B07": "Word Counter - Ask the user for a sentence and return the number of words. (Python)",
    "B08": "Fibonacci Sequence - Print the first n numbers in the Fibonacci sequence. (Python)",
    "B09": "Prime Number Checker - Ask the user for a number and determine if it's a prime. (Python)",
    "B10": "Password Strength Checker - Check if a password contains at least 8 characters, a number, and a special character. (Python)",
    "B11": "Rock, Paper, Scissors Game - Build a simple Rock-Paper-Scissors game against the computer. (Python)",
    "B12": "Shopping List App - Let the user add, view, and remove items from a shopping list stored in a list. (Python)",
    "B13": "Simple Login System - Hardcode a username and password, and ask the user to log in. (Python)",
    "B14": "Grade Calculator - Let the user input marks for 5 subjects and calculate the average and letter grade. (Python)",
    "B15": "Tip Calculator - Ask the user for the bill amount and tip percentage, then calculate the total. (Python)",
    "B16": "Even or Odd Checker - Prompt the user for a number and display whether it's even or odd. (JavaScript)",
    "B17": "Number Guessing Game - Generate a random number and let the user guess until they get it right. (JavaScript)",
    "B18": "Simple Calculator - Accept two numbers and an operator from the user and display the result. (JavaScript)",
    "B19": "Palindrome Checker - Check if a given string is a palindrome. (JavaScript)",
    "B20": "Multiplication Table Generator - Prompt for a number and show its multiplication table. (JavaScript)",
    "B21": "Countdown Timer - Prompt for seconds and countdown in real-time. (JavaScript)",
    "B22": "Word Counter - Count the number of words in a sentence entered by the user. (JavaScript)",
    "B23": "Fibonacci Sequence - Print the first n numbers in the Fibonacci sequence. (JavaScript)",
    "B24": "Prime Number Checker - Check whether a user-entered number is prime. (JavaScript)",
    "B25": "Password Strength Checker - Validate if a password meets common strength rules. (JavaScript)",
    "B26": "Rock, Paper, Scissors - A game where the user plays against the computer. (JavaScript)",
    "B27": "To-Do List - Add and remove items dynamically in an HTML list. (JavaScript)",
    "B28": "Simple Form Validation - Validate a form with fields like name, email, and password. (JavaScript)",
    "B29": "Grade Calculator - Calculate average and letter grade from input scores. (JavaScript)",
    "B30": "Tip Calculator - Take bill amount and tip percentage, and show the total. (JavaScript)",
    "I01": "To-Do List CLI App - Create a command-line to-do list app that saves tasks to a file. (Python)",
    "I02": "Contact Book with Search - Build a contact manager with add, view, search, and delete features using a dictionary or JSON file. (Python)",
    "I03": "Unit Converter - Convert units like temperature, length, and weight (e.g., Celsius to Fahrenheit, meters to feet). (Python)",
    "I04": "Currency Converter using API - Use a real-time exchange rate API to convert currencies. (Python)",
    "I05": "Weather App (API) - Fetch and display weather data using the OpenWeatherMap API. (Python)",
    "I06": "Quiz Game with Score Tracking - Create a quiz app that tracks the score and gives feedback. (Python)",
    "I07": "Text-Based Adventure Game - Build an interactive adventure game with choices, rooms, and inventory. (Python)",
    "I08": "Simple Web Scraper - Use requests and BeautifulSoup to scrape data from a webpage. (Python)",
    "I09": "Markdown to HTML Converter - Convert simple Markdown syntax (like # and **) into HTML. (Python)",
    "I10": "Password Generator - Generate strong random passwords with customizable length and character types. (Python)",
    "I11": "Bank Account Class - Use OOP to create a bank account system with deposit, withdraw, and balance methods. (Python)",
    "I12": "Hangman Game - Build a playable Hangman game with word selection and letter tracking. (Python)",
    "I13": "File Duplicates Finder - Find duplicate files in a directory by comparing file sizes or hashes. (Python)",
    "I14": "Simple Budget Tracker - Track income and expenses with basic reporting by category. (Python)",
    "I15": "Timer and Pomodoro Clock - Create a CLI or GUI Pomodoro timer with work/break cycles. (Python)",
    "I16": "CSV File Analyzer - Load and analyze a CSV file to get column stats and search data. (Python)",
    "I17": "Typing Speed Test - Measure typing speed in words per minute based on a given sentence. (Python)",
    "I18": "Basic Encryption/Decryption Tool - Implement a Caesar or substitution cipher to encode and decode messages. (Python)",
    "I19": "Calendar Event Organizer - Build a CLI calendar that allows adding, viewing, and deleting events. (Python)",
    "I20": "Basic Chatbot - Create a rule-based chatbot that responds to certain keywords or questions. (Python)",
    "I21": "To-Do List with LocalStorage - Save a to-do list in the browser's localStorage. (JavaScript)",
    "I22": "Contact Book - Create a contact manager with search and delete features. (JavaScript)",
    "I23": "Unit Converter - Convert values between metric and imperial units. (JavaScript)",
    "I24": "Currency Converter using API - Convert currencies using a free exchange rate API. (JavaScript)",
    "I25": "Weather App using API - Fetch and display weather using a weather API and user input. (JavaScript)",
    "I26": "Quiz Game - Interactive quiz with multiple questions and score tracking. (JavaScript)",
    "I27": "Text Adventure Game - Simple choice-based game in the browser. (JavaScript)",
    "I28": "Markdown Previewer - Convert Markdown input to HTML in real-time. (JavaScript)",
    "I29": "Password Generator - Create strong passwords with user-specified options. (JavaScript)",
    "I30": "Bank App (OOP) - Simulate a bank account using object-oriented principles. (JavaScript)",
    "I31": "Hangman Game - Classic hangman game in the browser. (JavaScript)",
    "I32": "Image Carousel - Build an auto-sliding image gallery. (JavaScript)",
    "I33": "Expense Tracker - Track and display income/expenses with simple charts. (JavaScript)",
    "I34": "Pomodoro Timer - Work/break timer with configurable intervals. (JavaScript)",
    "I35": "CSV Parser - Parse CSV input and display it in a table. (JavaScript)",
    "I36": "Typing Speed Test - Measure and display typing speed in real-time. (JavaScript)",
    "I37": "Encryption Tool - Encode/decode text using Caesar cipher. (JavaScript)",
    "I38": "Calendar App - Add and view events with local persistence. (JavaScript)",
    "I39": "Basic Chatbot - Rule-based chatbot in the browser. (JavaScript)",
    "I40": "Form Wizard - Multi-step form with progress tracking. (JavaScript)",
    "A01": "Asynchronous Web Crawler - Use aiohttp and asyncio to crawl multiple web pages concurrently. (Python)",
    "A02": "RESTful API with Flask or FastAPI - Build a full REST API with CRUD operations and connect it to a database. (Python)",
    "A03": "Chat Application with Sockets - Create a real-time terminal-based chat app using Python sockets (TCP). (Python)",
    "A04": "Multithreaded File Downloader - Download multiple files concurrently using threading or multiprocessing. (Python)",
    "A05": "Machine Learning Model Trainer - Use scikit-learn to train and evaluate a model on a real dataset. (Python)",
    "A06": "Image Editor - Build a basic image editor (crop, rotate, filter) using Pillow or OpenCV. (Python)",
    "A07": "Blockchain Simulation - Create a simple blockchain with proof-of-work, mining, and validation features. (Python)",
    "A08": "Portfolio Website Generator - Write a Python script that generates a static portfolio site from a config file. (Python)",
    "A09": "Database Backup Automation - Automate backups of a database and upload to a cloud service like AWS or Google Drive. (Python)",
    "A10": "PDF Report Generator - Generate styled PDF reports with tables and charts using ReportLab or fpdf. (Python)",
    "A11": "Custom CLI Tool with argparse / Click - Build a command-line tool with multiple arguments, flags, and help menus. (Python)",
    "A12": "Web Automation with Selenium - Automate browser tasks like form submission and data scraping from JavaScript-heavy pages. (Python)",
    "A13": "Email Parser and Categorizer - Parse and categorize emails from .eml files or an IMAP inbox. (Python)",
    "A14": "Task Scheduler - Build a lightweight task scheduler that runs Python code at specified times or intervals. (Python)",
    "A15": "Data Dashboard with Dash or Streamlit - Create an interactive dashboard to explore and visualize datasets. (Python)",
    "A16": "Compiler or Interpreter for a Mini Language - Implement a small language parser and evaluator using recursive descent or lark. (Python)",
    "A17": "AI Chatbot with NLP - Build a chatbot that understands user input using NLP libraries like spaCy or NLTK. (Python)",
    "A18": "Custom Encryption Algorithm - Create and test a custom encryption and decryption system (educational purpose only). (Python)",
    "A19": "Face Recognition System - Use OpenCV and face_recognition to detect and identify faces in real time. (Python)",
    "A20": "Virtual File System in Memory - Simulate a file system in memory with support for directories and basic commands. (Python)",
    "A21": "Single Page App (SPA) Router - Build a router for a multi-page SPA without frameworks. (JavaScript)",
    "A22": "Real-Time Chat App - Create a chat app using WebSockets (Node.js backend). (JavaScript)",
    "A23": "Kanban Board - Build a drag-and-drop task board using HTML5 Drag and Drop API. (JavaScript)",
    "A24": "Multifile Uploader - Upload multiple files with progress bars using Fetch API. (JavaScript)",
    "A25": "Machine Learning with TensorFlow.js - Train and run a simple ML model in the browser. (JavaScript)",
    "A26": "Image Editor - Build an editor with crop, rotate, brightness, and filters. (JavaScript)",
    "A27": "Blockchain Demo - Simulate a blockchain and visualize transactions in the browser. (JavaScript)",
    "A28": "Portfolio Generator - Generate a portfolio site from JSON data. (JavaScript)",
    "A29": "Authentication System - Implement login, signup, and session management (Node.js + JWT). (JavaScript)",
    "A30": "PDF Invoice Generator - Generate styled PDF invoices from input forms. (JavaScript)",
    "A31": "CLI Tool with Node.js - Build a terminal command using Node (e.g. file organizer). (JavaScript)",
    "A32": "Web Scraper (Node.js) - Scrape web data using cheerio and display it. (JavaScript)",
    "A33": "Email Client UI - Build a front-end email UI with folders, search, and mock messages. (JavaScript)",
    "A34": "Scheduler with Notifications - Create scheduled tasks with browser notifications. (JavaScript)",
    "A35": "Dashboard with Charts - Build a dashboard with interactive charts using Chart.js or D3.js. (JavaScript)",
    "A36": "Code Editor - Build a basic in-browser code editor using CodeMirror or Monaco. (JavaScript)",
    "A37": "Voice Assistant - Create a voice-controlled app using the Web Speech API. (JavaScript)",
    "A38": "WebRTC Video Chat - Build a peer-to-peer video chat app using WebRTC. (JavaScript)",
    "A39": "Face Detection App - Detect faces in webcam video using face-api.js. (JavaScript)",
    "A40": "Virtual File System UI - Simulate a file manager with folders, files, and operations. (JavaScript)"
}