challenge_dict = { 
    "B01": "Even or Odd Checker - Ask the user for a number and print whether it's even or odd.",
    "B02": "Number Guessing Game - Generate a random number between 1 and 10, and ask the user to guess it.",
    "B03": "Simple Calculator - Let the user input two numbers and an operator (+, -, *, /) and return the result.",
    "B04": "Palindrome Checker - Check if a given string (like 'radar') reads the same backward.",
    "B05": "Multiplication Table Generator - Ask the user for a number and print its multiplication table up to 10.",
    "B06": "Countdown Timer - Ask for a number of seconds, and count down to 0, printing each second.",
    "B07": "Word Counter - Ask the user for a sentence and return the number of words.",
    "B08": "Fibonacci Sequence - Print the first n numbers in the Fibonacci sequence.",
    "B09": "Prime Number Checker - Ask the user for a number and determine if it's a prime.",
    "B10": "Password Strength Checker - Check if a password contains at least 8 characters, a number, and a special character.",
    "B11": "Rock, Paper, Scissors Game - Build a simple Rock-Paper-Scissors game against the computer.",
    "B12": "Shopping List App - Let the user add, view, and remove items from a shopping list stored in a list.",
    "B13": "Simple Login System - Hardcode a username and password, and ask the user to log in.",
    "B14": "Grade Calculator - Let the user input marks for 5 subjects and calculate the average and letter grade.",
    "B15": "Tip Calculator - Ask the user for the bill amount and tip percentage, then calculate the total.",
    "I01": "To-Do List CLI App - Create a command-line to-do list app that saves tasks to a file.",
    "I02": "Contact Book with Search - Build a contact manager with add, view, search, and delete features using a dictionary or JSON file.",
    "I03": "Unit Converter - Convert units like temperature, length, and weight (e.g., Celsius to Fahrenheit, meters to feet).",
    "I04": "Currency Converter using API - Use a real-time exchange rate API to convert currencies.",
    "I05": "Weather App (API) - Fetch and display weather data using the OpenWeatherMap API.",
    "I06": "Quiz Game with Score Tracking - Create a quiz app that tracks the score and gives feedback.",
    "I07": "Text-Based Adventure Game - Build an interactive adventure game with choices, rooms, and inventory.",
    "I08": "Simple Web Scraper - Use requests and BeautifulSoup to scrape data from a webpage.",
    "I09": "Markdown to HTML Converter - Convert simple Markdown syntax (like # and **) into HTML.",
    "I10": "Password Generator - Generate strong random passwords with customizable length and character types.",
    "I11": "Bank Account Class - Use OOP to create a bank account system with deposit, withdraw, and balance methods.",
    "I12": "Hangman Game - Build a playable Hangman game with word selection and letter tracking.",
    "I13": "File Duplicates Finder - Find duplicate files in a directory by comparing file sizes or hashes.",
    "I14": "Simple Budget Tracker - Track income and expenses with basic reporting by category.",
    "I15": "Timer and Pomodoro Clock - Create a CLI or GUI Pomodoro timer with work/break cycles.",
    "I16": "CSV File Analyzer - Load and analyze a CSV file to get column stats and search data.",
    "I17": "Typing Speed Test - Measure typing speed in words per minute based on a given sentence.",
    "I18": "Basic Encryption/Decryption Tool - Implement a Caesar or substitution cipher to encode and decode messages.",
    "I19": "Calendar Event Organizer - Build a CLI calendar that allows adding, viewing, and deleting events.",
    "I20": "Basic Chatbot - Create a rule-based chatbot that responds to certain keywords or questions.",
    "A01": "Asynchronous Web Crawler - Use aiohttp and asyncio to crawl multiple web pages concurrently.",
    "A02": "RESTful API with Flask or FastAPI - Build a full REST API with CRUD operations and connect it to a database.",
    "A03": "Chat Application with Sockets - Create a real-time terminal-based chat app using Python sockets (TCP).",
    "A04": "Multithreaded File Downloader - Download multiple files concurrently using threading or multiprocessing.",
    "A05": "Machine Learning Model Trainer - Use scikit-learn to train and evaluate a model on a real dataset.",
    "A06": "Image Editor - Build a basic image editor (crop, rotate, filter) using Pillow or OpenCV.",
    "A07": "Blockchain Simulation - Create a simple blockchain with proof-of-work, mining, and validation features.",
    "A08": "Portfolio Website Generator - Write a Python script that generates a static portfolio site from a config file.",
    "A09": "Database Backup Automation - Automate backups of a database and upload to a cloud service like AWS or Google Drive.",
    "A10": "PDF Report Generator - Generate styled PDF reports with tables and charts using ReportLab or fpdf.",
    "A11": "Custom CLI Tool with argparse / Click - Build a command-line tool with multiple arguments, flags, and help menus.",
    "A12": "Web Automation with Selenium - Automate browser tasks like form submission and data scraping from JavaScript-heavy pages.",
    "A13": "Email Parser and Categorizer - Parse and categorize emails from .eml files or an IMAP inbox.",
    "A14": "Task Scheduler - Build a lightweight task scheduler that runs Python code at specified times or intervals.",
    "A15": "Data Dashboard with Dash or Streamlit - Create an interactive dashboard to explore and visualize datasets.",
    "A16": "Compiler or Interpreter for a Mini Language - Implement a small language parser and evaluator using recursive descent or lark.",
    "A17": "AI Chatbot with NLP - Build a chatbot that understands user input using NLP libraries like spaCy or NLTK.",
    "A18": "Custom Encryption Algorithm - Create and test a custom encryption and decryption system (educational purpose only).",
    "A19": "Face Recognition System - Use OpenCV and face_recognition to detect and identify faces in real time.",
    "A20": "Virtual File System in Memory - Simulate a file system in memory with support for directories and basic commands."
    }